Updated to Raspian streach -- see release notes for details

diff --git a/runme b/runme
--- a/runme
+++ b/runme
@@ -12,6 +12,8 @@
 
 _FREESPACEWANTED=500 # MByte of free space required to install
 FREESPACEWANTED=$_FREESPACEWANTED
+_PART_SIZE='+3.5G' # Used by fdisk, root  partition size
+
 UPGRADE=""  # Default to full install
 
 SERVER_PORT=9191      # Default secure port
@@ -24,6 +26,80 @@ PP_USER="papercut"  # User account to own and run papecut
 ask() {
     read -p "$1" -r < /dev/tty
     echo "$REPLY"
+}
+
+# This code is adapted from https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config
+resize_sd() {
+
+  ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
+
+  PART_NUM=${ROOT_PART#mmcblk0p}
+  if [ "$PART_NUM" = "$ROOT_PART" ]; then
+      whiptail --msgbox "$ROOT_PART is not an SD card. Don't know how to expand" 20 60 2
+      return 0
+  fi
+
+# NOTE: the NOOBS partition layout confuses parted. For now, let's only
+# agree to work with a sufficiently simple partition layout
+  if [ "$PART_NUM" -ne 2 ]; then
+    whiptail --msgbox "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway." 20 60 2
+    return 0
+  fi
+
+  LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)
+  if [ $LAST_PART_NUM -ne $PART_NUM ]; then
+    whiptail --msgbox "$ROOT_PART is not the last partition. Don't know how to expand" 20 60 2
+    return 0
+  fi
+
+# Get the starting offset of the root partition
+  PART_START=$(sudo parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
+  [ "$PART_START" ] || return 1
+# Return value will likely be error for fdisk as it fails to reload the
+# partition table because the root fs is mounted
+  sudo fdisk /dev/mmcblk0 <<EOF
+p
+d
+$PART_NUM
+n
+p
+$PART_NUM
+$PART_START
+$_PART_SIZE
+p
+w
+EOF
+
+
+# now set up an init.d script
+cat <<EOF | sudo tee > /dev/null  /etc/init.d/resize2fs_once &&
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          resize2fs_once
+# Required-Start:
+# Required-Stop:
+# Default-Start: 3
+# Default-Stop:
+# Short-Description: Resize the root filesystem to fill partition
+# Description:
+### END INIT INFO
+. /lib/lsb/init-functions
+case "\$1" in
+  start)
+    log_daemon_msg "Starting resize2fs_once" &&
+    resize2fs /dev/$ROOT_PART &&
+    update-rc.d resize2fs_once remove &&
+    rm /etc/init.d/resize2fs_once &&
+    log_end_msg \$?
+    ;;
+  *)
+    echo "Usage: \$0 start" >&2
+    exit 3
+    ;;
+esac
+EOF
+sudo chmod +x /etc/init.d/resize2fs_once &&
+  sudo update-rc.d resize2fs_once defaults
 }
 
 usage() {
@@ -115,8 +191,7 @@ if [[ -n "$FREESPACEWANTED" && $(df -m --output=avail / | tail -1) -lt $FREESPAC
     echo N.B. If you have NOT already autosized your image to fit all the space on the SD card
     echo 'I can resize the image for you to 3G which will be enough if you are using Jessie "lite"'
     if [[ $(ask "Do you want to resize the SD card image to 3G?  [N/y]") =~ [Yy] ]] ; then
-      sudo parted /dev/mmcblk0  resizepart 2 3G
-      sudo resize2fs /dev/mmcblk0p2
+      resize_sd
       echo The Pi will now reboot emmdialty to complete the resize. Please rerun $0 again
       ask "Press any key to continue"
       sudo init 6
@@ -258,6 +333,12 @@ if ! grep "prompt4Locale" $PP_HOME/.profile ; then
 
 cat <<EOF | sudo tee -a $PP_HOME/.profile
 
+echo -n "Network hostname is "
+hostname
+echo -n "Network IP addresses are "
+hostname -I
+read -p "Press any key to continue" -n 1 < /dev/tty
+
 if [[ -e /boot/prompt4Locale ]] ; then
     echo
     echo "WARNING:"
@@ -301,7 +382,6 @@ Section "ServerFlags"
 EndSection
 EOF
 
-
 echo We can put some host setttings in the /boot/machine.local and you can edit them on your laptop as needed
 
 echo
@@ -336,12 +416,10 @@ newhostname=$newhostname  # Host for /etc/host
 #newhostname=<fixed hostname>  # Or use a different hostname instead
 #newhostname=$dynhostname
 #
-# To enable a wifi network uncomment and set the following values as needed
+# To enable a wifi network add the following content to a file /boot/wpa_supplicant.conf
+# and reboot the Raspiberry Pi
+# TODO -- add example here.
 #
-#ssid=SSID
-#psk=PSK Passphrase
-#id_str=ID  # Optional -- will use SSID if not present
-#interface=wlan0 # Optional. Usually defaults to wlan0
 EOF
 
 cat <<'EOF' | sudo tee /usr/local/sbin/config-hostname > /dev/null
